# This is a sample config file to show the required values to set
# Valuse should be updated to match your service and alerting desires
service: kessel-inventory
namespace: kessel-stage
env: stage
app_team: ciam-authz
dashboard_link: https://test.com
app_console_link: https://console.com/app
connector_console_link: https://console.com/connector
app_sop: https://sop.com
outbox_topic: outbox.event.kessel.tuples
severity: medium
job_name: kessel-inventory-api
connector: kessel-inventory-source-connector
