# This config file lists the required values to set in App Interface
# It is used for testing changed in this repo only
# Values should be updated to match your service and alerting desires
service: <Name of the application service - must match alertingService name in App Interface>
namespace: <Namespace in cluster where service lives>
env: <Env for alert (stage, prod, etc)>
app_team: <App team name (correlates to Slack handle)>
dashboard_link: <Link to RDS Dashboard in Grafana>
app_console_link: <Link to App in Cluster Console>
connector_console_link: <Link to Kafka Connect object in Cluster Console>
app_sop: <Link to App SOP in App Interface or Runbooks link>
severity: <Alert severity (set on all alerts)>
outbox_topic: <Name of Kafka Topic used for outbox events>
job_name: <kubernetes job name (matches ServiceMonitor name)>s
connector: <Name of Kafka Connector CR configured for Debezium>
