{
 "title": "{{SERVICE_NAME}} Consumer Status",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Consumer Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Consumers",
   "type": "stat",
   "description": "Number of active consumers (should match number of replicas, may not indicate they are actively consuming depending on partition count)",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(consumer_stats_state{state=\"up\", job=\"{{JOB_NAME}}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Msgs in Queue",
   "type": "stat",
   "description": "Number of messages remaining in topic to be processed",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consumer_stats_replyq{job=\"{{JOB_NAME}}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Rebalance",
   "type": "stat",
   "description": "How long since last rebalance occurred",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(consumer_stats_rebalance_age{job=\"{{JOB_NAME}}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Lag (messages)",
   "type": "timeseries",
   "description": "Messages are committed in batches of ~10. Lag up to 10 messages can be expected",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_topic_sum_lag{topic=~\"{{TOPIC_NAME}}\", job=\"{{JOB_NAME}}\"}",
     "legendFormat": "{topic=\"{{topic}}\", group=\"{{group}}\"}"
    }
   ]
  },
  {
   "title": "Kafka Lag (seconds)",
   "type": "timeseries",
   "description": "Messages are committed in batches of ~10. Lag up to 10 messages can be expected",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic, group) (kafka_consumergroup_group_lag_seconds{topic=~\"{{TOPIC_NAME}}\", job=\"{{JOB_NAME}}\"})",
     "legendFormat": "{topic=\"{{topic}}\", group=\"{{group}}\"}"
    }
   ]
  },
  {
   "title": "Rebalance Events",
   "type": "timeseries",
   "description": "Captures how many rebalance events have occurred over set interval",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(consumer_stats_rebalance_cnt_total{job=\"{{JOB_NAME}}\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msgs_processed_total{job=\"{{JOB_NAME}}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msg_process_failures_total{job=\"{{JOB_NAME}}\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"{{JOB_NAME}}\"}[$__rate_interval])) or sum(up{job=\"{{JOB_NAME}}\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Error Rate",
   "type": "timeseries",
   "description": "Errors related to the Consumer and not message processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(consumer_errors_total{job=\"{{JOB_NAME}}\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"{{JOB_NAME}}\"}[$__rate_interval])) or sum(up{job=\"{{JOB_NAME}}\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Error Events",
   "type": "table",
   "description": "Recent Kafka Error Event Messages Processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "consumer_kafka_error_events_total{job=\"{{JOB_NAME}}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Outbox Events",
   "type": "stat",
   "description": "(in $range)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_event_writes_total{job=\"{{JOB_NAME}}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "stat",
   "description": "(in $range)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(consumer_msgs_processed_total{job=\"{{JOB_NAME}}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "End to end replication lag",
   "type": "timeseries",
   "description": "Lag from point where resource is written to outbox table, to consumed and processed by inventory consumer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(outbox_event_writes_total{job=\"{{JOB_NAME}}\"}[3m])) - sum(rate(consumer_msgs_processed_total{job=\"{{JOB_NAME}}\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}