database.server.name: ${SERVICE_NAME}
database.dbname: ${secrets:${DB_SECRET_NAME}:db.name}
database.hostname: ${secrets:${DB_SECRET_NAME}:db.host}
database.port: ${secrets:${DB_SECRET_NAME}:db.port}
database.user: ${secrets:${DB_SECRET_NAME}:db.user}
database.password: ${secrets:${DB_SECRET_NAME}:db.password}
topic.prefix: ${SERVICE_NAME}
table.include.list: ${OUTBOX_TABLE_NAME}
transforms: outbox
transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
# Headers are useful for passing info about the event to the consumer, for example operation type (Create/Update/Delete)
# you can define your own extra headers by adding columns in your table, then uncommenting the below
# and specifying the names of these columns and set them has header fields
# transforms.outbox.table.fields.additional.placement: HEADER-NAME-1:header, HEADER-NAME-2:header, etc
transforms.outbox.table.expand.json.payload: true
value.converter: org.apache.kafka.connect.json.JsonConverter
plugin.name: pgoutput
heartbeat.interval.ms: ${DEBEZIUM_HEARTBEAT_INTERVAL_MS}
heartbeat.action.query: ${DEBEZIUM_ACTION_QUERY}
topic.heartbeat.prefix: ${TOPIC_HEARTBEAT_PREFIX}
poll.interval.ms: ${DEBEZIUM_POLL_INTERVAL_MS}
